package dev.korafx.framework.theme

import kotlin.test.assertContains

internal fun assertCommonControlStyles(css: String) {
    listOf(
        ".combo-box-base",
        ".combo-box-base .text-field",
        ".combo-box-base .list-cell",
        ".combo-box-base:showing",
        ".combo-box-popup .list-view",
        ".combo-box-popup .list-cell:hover",
        ".combo-box-popup .list-cell:selected",
        ".choice-box",
        ".choice-box .label",
        ".choice-box > .label",
        ".choice-box .open-button",
        ".choice-box:pressed",
        ".choice-box .context-menu",
        ".choice-box .menu-item:selected",
        ".date-picker",
        ".date-picker .text-field",
        ".date-picker-popup",
        ".date-picker-popup .month-year-pane",
        ".date-picker-popup .day-cell:selected",
        ".color-picker .color-picker-label",
        ".color-picker.split-button > .color-picker-label",
        ".color-palette",
        ".color-palette .color-square",
        ".spinner",
        ".spinner .text-field",
        ".text-field:hover",
        ".text-area:hover",
        ".list-cell:hover",
        ".list-cell:selected",
        ".list-cell:empty",
        ".tree-table-row-cell:empty",
        ".tree-table-view:focused",
        ".table-view .column-header",
        ".table-view .column-header:hover",
        ".table-cell",
        ".tree-view .tree-cell .tree-disclosure-node .arrow",
        ".tree-cell:selected .tree-disclosure-node .arrow",
        ".hyperlink",
        ".hyperlink:hover",
        ".hyperlink.route-link-active",
        ".hyperlink:focused",
        ".hyperlink:armed",
        ".tree-table-view",
        ".tree-table-cell",
        ".tree-table-view .column-header",
        ".tree-table-view .tree-table-row-cell .tree-disclosure-node .arrow",
        ".tree-table-view .placeholder .label",
        ".tab-pane .tab:selected",
        ".tab-pane .tab:focused",
        ".tab-pane .tab:hover",
        ".tab-pane .tab:pressed",
        ".tab-pane .tab:disabled",
        ".tab-pane .tab-close-button",
        ".tab-pane .tab-close-button:hover",
        ".titled-pane > .title",
        ".titled-pane:hover > .title",
        ".titled-pane:expanded > .title",
        ".titled-pane > .title > .arrow-button",
        ".accordion > .titled-pane:expanded > .title",
        ".slider .thumb",
        ".progress-indicator > .determinate-indicator > .indicator",
        ".progress-indicator:indeterminate .segment",
        ".pagination .pagination-control .page-number:selected",
        ".pagination .pagination-control .page-number:hover",
        ".pagination .pagination-control .page-number:pressed",
        ".pagination .pagination-control .button:hover",
        ".pagination .pagination-control .button:pressed",
        ".scroll-pane > .viewport",
        ".scroll-bar .thumb",
        ".scroll-bar .thumb:pressed",
        ".scroll-bar:disabled",
        ".scroll-bar .increment-button",
        ".tooltip",
        ".dialog-pane",
        ".dialog-pane > .header-panel",
        ".dialog-pane > .button-bar",
        ".button-bar > .container",
    ).forEach { selector ->
        assertContains(css, selector)
    }
}

internal fun assertWorkbenchControlStyles(css: String) {
    listOf(
        ".tab-workspace",
        ".tab-workspace-empty-pane",
        ".tab-workspace-empty",
        ".tab-workspace .tab-workspace-tab-dirty .tab-label",
        ".tab-workspace-dirty-marker",
        ".border-layout",
        ".border-layout-top",
        ".border-layout-center",
        ".workspace-layout",
        ".workspace-layout-frame",
        ".workspace-layout-top-bar",
        ".workspace-layout-navigation",
        ".workspace-layout-content",
        ".workspace-layout-details",
        ".workspace-layout-status",
        ".workspace-layout-overlay",
        ".workspace-layout-overlay-item",
        ".kora-window-frame",
        ".kora-window-frame.kora-window-transparent",
        ".kora-window-frame.kora-window-rounded",
        ".kora-window-titlebar",
        ".kora-window-titlebar-content",
        ".button.kora-window-button",
        ".button.kora-window-close-button:hover",
        ".app-toolbar",
        ".toolbar-group",
        ".app-toolbar-title",
        ".app-toolbar-subtitle",
        ".hero-banner",
        ".hero-banner-title",
        ".hero-banner-content",
        ".app-shell",
        ".app-shell-frame",
        ".app-shell-body",
        ".app-shell-top-bar",
        ".app-shell-navigation",
        ".app-shell-content",
        ".app-shell-details",
        ".app-shell-footer",
        ".app-shell-overlay-item",
    ).forEach { selector ->
        assertContains(css, selector)
    }
}
