package dev.korafx.framework.theme

import kotlin.test.Test
import kotlin.test.assertContains

class ThemeStylesheetFactoryTest {
    @Test
    fun `stylesheet contains token values`() {
        val material = BuiltInThemes.MaterialLight
        val css = ThemeStylesheetFactory.render(material)
        val states = material.tokens.states

        assertContains(css, ".root.${ThemeStyleClass.Root}")
        assertContains(css, "-fx-background-color: #FFFBFE;")
        assertContains(css, "-fx-font-family: \"Roboto\", \"Segoe UI\", \"Microsoft YaHei UI\", sans-serif;")
        assertContains(css, "-fx-font-size: 14px;")
        assertContains(css, "-fx-selection-bar: ${states.selected};")
        assertContains(css, "-fx-selection-bar-text: ${states.selectedText};")
        assertContains(css, "-fx-cell-hover-color: ${states.rowHover};")
        assertContains(css, "-fx-background-radius: 12px;")
        assertContains(css, "-fx-background-radius: 16px;")
        assertContains(css, "-fx-padding: 10 16 10 16;")
        assertContains(css, "-fx-background-color: ${states.controlHover};")
        assertContains(css, "-fx-background-color: ${states.surfaceHover};")
        assertContains(css, "-fx-opacity: 0.56;")
        assertContains(css, "-fx-effect: dropshadow(gaussian, rgba(0, 0, 0, 0.06), 10, 0.10, 0, 2);")
        assertContains(css, "-fx-effect: dropshadow(gaussian, rgba(0, 0, 0, 0.14), 14, 0.12, 0, 4);")
        assertContains(css, ".button.nav-button-active")
        assertContains(css, ".button.route-button")
        assertContains(css, ".button.route-button-active")
        assertContains(css, ".menu-button > .label")
        assertContains(css, ".menu-button > .arrow-button")
        assertContains(css, ".menu-button > .arrow-button > .arrow")
        assertContains(css, ".split-menu-button")
        assertContains(css, ".split-menu-button > .label")
        assertContains(css, ".split-menu-button > .arrow-button")
        assertContains(css, ".split-menu-button:armed > .label")
        assertContains(css, ".split-menu-button:showing > .arrow-button")
        assertContains(css, ".split-menu-button:focused")
        assertContains(css, ".context-menu")
        assertContains(css, ".menu-item:selected")
        assertContains(css, ".menu-item:disabled")
        assertContains(css, ".check-menu-item:selected")
        assertContains(css, ".check-menu-item:disabled")
        assertContains(css, ".radio-menu-item:selected")
        assertContains(css, ".radio-menu-item:disabled")
        assertContains(css, ".menu-item:focused .label")
        assertContains(css, ".check-menu-item:checked > .left-container > .check")
        assertContains(css, ".menu-bar > .container > .menu-button")
        assertContains(css, ".menu-bar > .container > .menu-button:focused")
        assertContains(css, ".menu-bar > .container > .menu-button > .label")
        assertContains(css, ".menu-bar > .container > .menu-button:disabled")
        assertContains(css, ".menu-bar > .container > .menu-button:showing > .label")
        assertContains(css, "-fx-text-fill: ${material.tokens.colors.textPrimary};")
        assertContains(css, ".card")
        assertContains(css, ".section-title")
        assertContains(css, ".action-bar")
        assertContains(css, ".form")
        assertContains(css, ".form-item")
        assertContains(css, ".form-label")
        assertContains(css, ".form-helper")
        assertContains(css, ".validation-message")
        assertContains(css, ".submit-bar")
        assertContains(css, ".route-state-host")
        assertContains(css, ".badge")
        assertContains(css, ".chip")
        assertContains(css, ".chip.chip-selected")
        assertContains(css, ".tone-success")
        assertContains(css, ".tone-warning")
        assertContains(css, ".tone-danger")
        assertContains(css, ".metric-card")
        assertContains(css, ".metric-value")
        assertContains(css, ".alert-banner")
        assertContains(css, ".alert-title")
        assertContains(css, ".alert-message")
        assertContains(css, ".alert-action")
        assertContains(css, ".code-editor")
        assertContains(css, ".code-editor-toolbar")
        assertContains(css, ".code-editor-search")
        assertContains(css, ".code-editor-search-field")
        assertContains(css, ".code-editor-replace-label")
        assertContains(css, ".code-editor-replace-field")
        assertContains(css, ".code-editor-frame")
        assertContains(css, ".code-editor-line-numbers")
        assertContains(css, ".code-editor-line-number-active")
        assertContains(css, ".code-editor-area")
        assertContains(css, ".code-editor-status")
        assertContains(css, ".code-editor-status-text")
        assertContains(css, ".source-editor")
        assertContains(css, ".source-editor-toolbar")
        assertContains(css, ".source-editor-action")
        assertContains(css, ".source-editor-status")
        assertContains(css, ".source-editor-status-message")
        assertContains(css, ".source-editor-status-badge")
        assertContains(css, ".source-editor-diagnostics")
        assertContains(css, ".source-editor-diagnostic")
        assertContains(css, ".source-editor-result")
        assertContains(css, ".source-editor-diagnostic.tone-warning")
        assertContains(css, ".breadcrumb")
        assertContains(css, ".breadcrumb-item-link")
        assertContains(css, ".breadcrumb-item-current")
        assertContains(css, ".page-header")
        assertContains(css, ".page-header-title")
        assertContains(css, ".page-header-actions")
        assertContains(css, ".status-bar")
        assertContains(css, ".status-item")
        assertContains(css, ".app-shell")
        assertContains(css, ".app-shell-frame")
        assertContains(css, ".app-shell-body")
        assertContains(css, ".app-shell-top-bar")
        assertContains(css, ".app-shell-navigation")
        assertContains(css, ".app-shell-content")
        assertContains(css, ".app-shell-details")
        assertContains(css, ".app-shell-footer")
        assertContains(css, ".app-shell-overlay-item")
        assertContains(css, ".modal-card")
        assertContains(css, ".modal-backdrop")
        assertContains(css, ".snackbar")
        assertContains(css, ".toast-success")
        assertContains(css, "-fx-border-color: ${material.tokens.colors.success};")
        assertContains(css, "-fx-border-color: ${material.tokens.colors.danger};")
        assertContains(css, ".feedback-state")
        assertContains(css, ".feedback-graphic")
        assertContains(css, ".feedback-actions")
        assertContains(css, ".feedback-action")
        assertContains(css, ".loading-state-indicator")
    }

    @Test
    fun `stylesheet covers common JavaFX control skins`() {
        val css = ThemeStylesheetFactory.render(BuiltInThemes.MaterialLight)

        assertContains(css, ".combo-box-base")
        assertContains(css, ".combo-box-base .text-field")
        assertContains(css, ".combo-box-base .list-cell")
        assertContains(css, ".combo-box-base:showing")
        assertContains(css, ".combo-box-popup .list-view")
        assertContains(css, ".combo-box-popup .list-cell:hover")
        assertContains(css, ".combo-box-popup .list-cell:selected")
        assertContains(css, ".choice-box")
        assertContains(css, ".choice-box .label")
        assertContains(css, ".choice-box > .label")
        assertContains(css, ".choice-box .open-button")
        assertContains(css, ".choice-box:pressed")
        assertContains(css, ".choice-box .context-menu")
        assertContains(css, ".choice-box .menu-item:selected")
        assertContains(css, ".date-picker")
        assertContains(css, ".date-picker .text-field")
        assertContains(css, ".date-picker-popup")
        assertContains(css, ".date-picker-popup .month-year-pane")
        assertContains(css, ".date-picker-popup .day-cell:selected")
        assertContains(css, ".color-picker .color-picker-label")
        assertContains(css, ".color-picker.split-button > .color-picker-label")
        assertContains(css, ".color-palette")
        assertContains(css, ".color-palette .color-square")
        assertContains(css, ".spinner")
        assertContains(css, ".spinner .text-field")
        assertContains(css, ".text-field:hover")
        assertContains(css, ".text-area:hover")
        assertContains(css, ".list-cell:hover")
        assertContains(css, ".list-cell:selected")
        assertContains(css, ".list-cell:empty")
        assertContains(css, ".tree-table-row-cell:empty")
        assertContains(css, ".tree-table-view:focused")
        assertContains(css, ".table-view .column-header")
        assertContains(css, ".table-view .column-header:hover")
        assertContains(css, ".table-cell")
        assertContains(css, ".tree-view .tree-cell .tree-disclosure-node .arrow")
        assertContains(css, ".tree-cell:selected .tree-disclosure-node .arrow")
        assertContains(css, ".hyperlink")
        assertContains(css, ".hyperlink:hover")
        assertContains(css, ".hyperlink.route-link-active")
        assertContains(css, ".hyperlink:focused")
        assertContains(css, ".hyperlink:armed")
        assertContains(css, ".tree-table-view")
        assertContains(css, ".tree-table-cell")
        assertContains(css, ".tree-table-view .column-header")
        assertContains(css, ".tree-table-view .tree-table-row-cell .tree-disclosure-node .arrow")
        assertContains(css, ".tree-table-view .placeholder .label")
        assertContains(css, ".tab-pane .tab:selected")
        assertContains(css, ".tab-pane .tab:focused")
        assertContains(css, ".tab-pane .tab:hover")
        assertContains(css, ".tab-pane .tab:pressed")
        assertContains(css, ".tab-pane .tab:disabled")
        assertContains(css, ".tab-pane .tab-close-button")
        assertContains(css, ".tab-pane .tab-close-button:hover")
        assertContains(css, ".tab-workspace")
        assertContains(css, ".tab-workspace-empty-pane")
        assertContains(css, ".tab-workspace-empty")
        assertContains(css, ".tab-workspace .tab-workspace-tab-dirty .tab-label")
        assertContains(css, ".tab-workspace-dirty-marker")
        assertContains(css, ".titled-pane > .title")
        assertContains(css, ".titled-pane:hover > .title")
        assertContains(css, ".titled-pane:expanded > .title")
        assertContains(css, ".titled-pane > .title > .arrow-button")
        assertContains(css, ".accordion > .titled-pane:expanded > .title")
        assertContains(css, ".slider .thumb")
        assertContains(css, ".progress-indicator > .determinate-indicator > .indicator")
        assertContains(css, ".progress-indicator:indeterminate .segment")
        assertContains(css, ".pagination .pagination-control .page-number:selected")
        assertContains(css, ".pagination .pagination-control .page-number:hover")
        assertContains(css, ".pagination .pagination-control .page-number:pressed")
        assertContains(css, ".pagination .pagination-control .button:hover")
        assertContains(css, ".pagination .pagination-control .button:pressed")
        assertContains(css, ".scroll-pane > .viewport")
        assertContains(css, ".scroll-bar .thumb")
        assertContains(css, ".scroll-bar .thumb:pressed")
        assertContains(css, ".scroll-bar:disabled")
        assertContains(css, ".scroll-bar .increment-button")
        assertContains(css, ".tooltip")
        assertContains(css, ".dialog-pane")
        assertContains(css, ".dialog-pane > .header-panel")
        assertContains(css, ".dialog-pane > .button-bar")
        assertContains(css, ".button-bar > .container")
        assertContains(css, ".border-layout")
        assertContains(css, ".border-layout-top")
        assertContains(css, ".border-layout-center")
        assertContains(css, ".workspace-layout")
        assertContains(css, ".workspace-layout-frame")
        assertContains(css, ".workspace-layout-top-bar")
        assertContains(css, ".workspace-layout-navigation")
        assertContains(css, ".workspace-layout-content")
        assertContains(css, ".workspace-layout-details")
        assertContains(css, ".workspace-layout-status")
        assertContains(css, ".workspace-layout-overlay")
        assertContains(css, ".workspace-layout-overlay-item")
        assertContains(css, ".kora-window-frame")
        assertContains(css, ".kora-window-frame.kora-window-transparent")
        assertContains(css, ".kora-window-frame.kora-window-rounded")
        assertContains(css, ".kora-window-titlebar")
        assertContains(css, ".kora-window-titlebar-content")
        assertContains(css, ".button.kora-window-button")
        assertContains(css, ".button.kora-window-close-button:hover")
        assertContains(css, ".app-toolbar")
        assertContains(css, ".toolbar-group")
        assertContains(css, ".app-toolbar-title")
        assertContains(css, ".app-toolbar-subtitle")
        assertContains(css, ".hero-banner")
        assertContains(css, ".hero-banner-title")
        assertContains(css, ".hero-banner-content")
        assertContains(css, ".resource-explorer")
        assertContains(css, ".resource-explorer-search")
        assertContains(css, ".resource-explorer-breadcrumb")
        assertContains(css, ".resource-explorer-empty-state")
        assertContains(css, ".resource-explorer-tree")
        assertContains(css, ".resource-explorer-tree .tree-cell:empty")
        assertContains(css, ".resource-explorer-row-primary")
        assertContains(css, ".resource-explorer-row-secondary")
        assertContains(css, ".resource-explorer-row-status")
        assertContains(css, ".resource-explorer-cell")
        assertContains(css, ".resource-explorer-tree .tree-cell:selected")
        assertContains(css, ".editable-table")
        assertContains(css, ".editable-table-placeholder")
        assertContains(css, ".editable-table-text-column .label")
        assertContains(css, ".editable-table-cell-node")
        assertContains(css, ".editable-table .table-cell:editing")
        assertContains(css, ".editable-table-action")
        assertContains(css, ".data-grid")
        assertContains(css, ".data-grid-toolbar")
        assertContains(css, ".data-grid-search")
        assertContains(css, ".data-grid-toolbar-batch-action")
        assertContains(css, ".data-grid-toolbar-snapshot-action")
        assertContains(css, ".data-grid-column-visibility")
        assertContains(css, ".data-grid-column-visibility-item")
        assertContains(css, ".data-grid-table")
        assertContains(css, ".data-grid-row-dirty")
        assertContains(css, ".data-grid-footer")
        assertContains(css, ".data-grid-selection-summary")
        assertContains(css, ".data-grid-empty")
        assertContains(css, ".virtual-list")
        assertContains(css, ".virtual-list-list-view")
        assertContains(css, ".virtual-table")
        assertContains(css, ".virtual-table-table-view")
        assertContains(css, ".virtual-table-cell-node")
        assertContains(css, ".virtual-terminal")
        assertContains(css, ".virtual-terminal-list-view")
        assertContains(css, ".virtual-terminal-line-label")
        assertContains(css, ".terminal-success .virtual-terminal-line-label")
        assertContains(css, ".inspector-panel")
        assertContains(css, ".inspector-panel-header")
        assertContains(css, ".inspector-panel-title")
        assertContains(css, ".inspector-panel-metadata")
        assertContains(css, ".inspector-panel-section")
        assertContains(css, ".inspector-panel-property")
        assertContains(css, ".inspector-panel-actions")
        assertContains(css, ".button.inspector-panel-action")
        assertContains(css, ".inspector-panel-empty")
        assertContains(css, ".activity-timeline")
        assertContains(css, ".activity-timeline-group")
        assertContains(css, ".activity-timeline-row")
        assertContains(css, ".activity-timeline-marker")
        assertContains(css, ".activity-timeline-connector")
        assertContains(css, ".activity-timeline-event")
        assertContains(css, ".activity-timeline-action")
        assertContains(css, ".activity-timeline-row.tone-success .activity-timeline-marker")
        assertContains(css, ".command-palette")
        assertContains(css, ".command-palette-scrim")
        assertContains(css, ".command-palette-card")
        assertContains(css, ".command-palette-search")
        assertContains(css, ".command-palette-row")
        assertContains(css, ".command-palette-row-selected")
        assertContains(css, ".command-palette-title")
        assertContains(css, ".command-palette-group")
        assertContains(css, ".command-palette-empty")
    }

    @Test
    fun `fluent themes render windows typography and shell surfaces`() {
        listOf(BuiltInThemes.FluentLight, BuiltInThemes.FluentDark).forEach { theme ->
            val css = ThemeStylesheetFactory.render(theme)

            assertContains(css, "-fx-font-family: \"Segoe UI\", \"Microsoft YaHei UI\", sans-serif;")
            assertContains(css, "-fx-accent: ${theme.tokens.colors.primary};")
            assertContains(css, "-fx-background-color: ${theme.tokens.colors.surface};")
            assertContains(css, "-fx-background-radius: 4px;")
            assertContains(css, ".app-shell")
            assertContains(css, ".app-shell-frame")
            assertContains(css, ".app-shell-navigation")
            assertContains(css, ".workspace-layout")
            assertContains(css, ".workspace-layout-content")
        }
    }

    @Test
    fun `all built in themes render stylesheet from tokens`() {
        BuiltInThemes.all.forEach { theme ->
            val css = ThemeStylesheetFactory.render(theme)

            assertContains(css, "-fx-background-color: ${theme.tokens.colors.surface};")
            assertContains(css, "-fx-font-family: ${theme.tokens.typography.fontFamily};")
            assertContains(css, "-fx-font-size: ${theme.tokens.typography.baseSize}px;")
            assertContains(css, "-fx-background-radius: ${theme.tokens.radius}px;")
            assertContains(css, "-fx-background-color: ${theme.tokens.states.controlHover};")
            assertContains(css, "-fx-background-color: ${theme.tokens.states.surfaceHover};")
            assertContains(css, "-fx-selection-bar-text: ${theme.tokens.states.selectedText};")
            assertContains(css, "-fx-opacity: ${theme.tokens.states.disabledOpacity};")
            assertContains(css, "-fx-effect: ${theme.tokens.elevation.card};")
            assertContains(css, "-fx-effect: ${theme.tokens.elevation.dropdown};")
            assertContains(css, "-fx-border-color: ${theme.tokens.colors.success};")
            assertContains(css, "-fx-border-color: ${theme.tokens.colors.warning};")
            assertContains(css, "-fx-border-color: ${theme.tokens.colors.danger};")
            assertContains(css, "-fx-border-color: ${theme.tokens.colors.info};")
        }
    }
}
