package dev.korafx.framework.theme

import kotlin.test.Test
import kotlin.test.assertContains

class ThemeStylesheetFactoryTest {
    @Test
    fun `stylesheet contains token values`() {
        val material = BuiltInThemes.MaterialLight
        val css = ThemeStylesheetFactory.render(material)
        val states = material.tokens.states

        assertContains(css, ".root.${ThemeStyleClass.Root}")
        assertContains(css, "-fx-background-color: #FFFBFE;")
        assertContains(css, "-fx-font-family: \"Roboto\", \"Segoe UI\", \"Microsoft YaHei UI\", sans-serif;")
        assertContains(css, "-fx-font-size: 14px;")
        assertContains(css, "-fx-background-radius: 12px;")
        assertContains(css, "-fx-background-radius: 16px;")
        assertContains(css, "-fx-padding: 10 16 10 16;")
        assertContains(css, "-fx-background-color: ${states.controlHover};")
        assertContains(css, "-fx-background-color: ${states.surfaceHover};")
        assertContains(css, "-fx-opacity: 0.56;")
        assertContains(css, "-fx-effect: dropshadow(gaussian, rgba(0, 0, 0, 0.06), 10, 0.10, 0, 2);")
        assertContains(css, "-fx-effect: dropshadow(gaussian, rgba(0, 0, 0, 0.14), 14, 0.12, 0, 4);")
        assertContains(css, ".button.nav-button-active")
        assertContains(css, ".menu-button > .label")
        assertContains(css, ".menu-button > .arrow-button")
        assertContains(css, ".menu-button > .arrow-button > .arrow")
        assertContains(css, ".split-menu-button > .label")
        assertContains(css, ".split-menu-button > .arrow-button")
        assertContains(css, ".split-menu-button:armed > .label")
        assertContains(css, ".split-menu-button:showing > .arrow-button")
        assertContains(css, ".split-menu-button:focused")
        assertContains(css, ".context-menu")
        assertContains(css, ".menu-item:focused .label")
        assertContains(css, ".check-menu-item:checked > .left-container > .check")
        assertContains(css, ".menu-bar > .container > .menu-button")
        assertContains(css, ".menu-bar > .container > .menu-button > .label")
        assertContains(css, ".card")
        assertContains(css, ".section-title")
        assertContains(css, ".action-bar")
        assertContains(css, ".form")
        assertContains(css, ".form-item")
        assertContains(css, ".form-label")
        assertContains(css, ".form-helper")
        assertContains(css, ".validation-message")
        assertContains(css, ".submit-bar")
        assertContains(css, ".route-state-host")
        assertContains(css, ".badge")
        assertContains(css, ".chip")
        assertContains(css, ".chip.chip-selected")
        assertContains(css, ".tone-success")
        assertContains(css, ".tone-warning")
        assertContains(css, ".tone-danger")
        assertContains(css, ".metric-card")
        assertContains(css, ".metric-value")
        assertContains(css, ".alert-banner")
        assertContains(css, ".alert-title")
        assertContains(css, ".alert-message")
        assertContains(css, ".alert-action")
        assertContains(css, ".code-editor")
        assertContains(css, ".code-editor-toolbar")
        assertContains(css, ".code-editor-area")
        assertContains(css, ".code-editor-status")
        assertContains(css, ".code-editor-status-text")
        assertContains(css, ".source-editor")
        assertContains(css, ".source-editor-toolbar")
        assertContains(css, ".source-editor-action")
        assertContains(css, ".source-editor-diagnostics")
        assertContains(css, ".source-editor-diagnostic")
        assertContains(css, ".source-editor-result")
        assertContains(css, ".source-editor-diagnostic.tone-warning")
        assertContains(css, ".app-shell")
        assertContains(css, ".modal-card")
        assertContains(css, ".modal-backdrop")
        assertContains(css, ".snackbar")
        assertContains(css, ".toast-success")
        assertContains(css, "-fx-border-color: ${material.tokens.colors.success};")
        assertContains(css, "-fx-border-color: ${material.tokens.colors.danger};")
        assertContains(css, ".feedback-state")
        assertContains(css, ".loading-state-indicator")
    }

    @Test
    fun `stylesheet covers common JavaFX control skins`() {
        val css = ThemeStylesheetFactory.render(BuiltInThemes.MaterialLight)

        assertContains(css, ".combo-box-base")
        assertContains(css, ".combo-box-base .text-field")
        assertContains(css, ".combo-box-base .list-cell")
        assertContains(css, ".combo-box-base:showing")
        assertContains(css, ".combo-box-popup .list-view")
        assertContains(css, ".combo-box-popup .list-cell:hover")
        assertContains(css, ".combo-box-popup .list-cell:selected")
        assertContains(css, ".choice-box")
        assertContains(css, ".choice-box .label")
        assertContains(css, ".choice-box .open-button")
        assertContains(css, ".choice-box .context-menu")
        assertContains(css, ".date-picker")
        assertContains(css, ".date-picker .text-field")
        assertContains(css, ".date-picker-popup")
        assertContains(css, ".date-picker-popup .month-year-pane")
        assertContains(css, ".date-picker-popup .day-cell:selected")
        assertContains(css, ".color-picker .color-picker-label")
        assertContains(css, ".color-picker.split-button > .color-picker-label")
        assertContains(css, ".color-palette")
        assertContains(css, ".color-palette .color-square")
        assertContains(css, ".spinner")
        assertContains(css, ".spinner .text-field")
        assertContains(css, ".list-cell:selected")
        assertContains(css, ".table-view .column-header")
        assertContains(css, ".table-cell")
        assertContains(css, ".tree-view .tree-cell .tree-disclosure-node .arrow")
        assertContains(css, ".tree-table-view")
        assertContains(css, ".tree-table-cell")
        assertContains(css, ".tree-table-view .column-header")
        assertContains(css, ".tree-table-view .tree-table-row-cell .tree-disclosure-node .arrow")
        assertContains(css, ".tree-table-view .placeholder .label")
        assertContains(css, ".tab-pane .tab:selected")
        assertContains(css, ".tab-pane .tab:focused")
        assertContains(css, ".tab-workspace")
        assertContains(css, ".tab-workspace-empty-pane")
        assertContains(css, ".tab-workspace-empty")
        assertContains(css, ".tab-workspace .tab-workspace-tab-dirty .tab-label")
        assertContains(css, ".tab-workspace-dirty-marker")
        assertContains(css, ".titled-pane > .title")
        assertContains(css, ".slider .thumb")
        assertContains(css, ".progress-indicator > .determinate-indicator > .indicator")
        assertContains(css, ".progress-indicator:indeterminate .segment")
        assertContains(css, ".pagination .pagination-control .page-number:selected")
        assertContains(css, ".scroll-pane > .viewport")
        assertContains(css, ".scroll-bar .thumb")
        assertContains(css, ".tooltip")
        assertContains(css, ".dialog-pane")
        assertContains(css, ".dialog-pane > .header-panel")
        assertContains(css, ".dialog-pane > .button-bar")
        assertContains(css, ".button-bar > .container")
        assertContains(css, ".border-layout")
        assertContains(css, ".border-layout-top")
        assertContains(css, ".border-layout-center")
        assertContains(css, ".workspace-layout")
        assertContains(css, ".workspace-layout-frame")
        assertContains(css, ".workspace-layout-top-bar")
        assertContains(css, ".workspace-layout-navigation")
        assertContains(css, ".workspace-layout-content")
        assertContains(css, ".workspace-layout-details")
        assertContains(css, ".workspace-layout-status")
        assertContains(css, ".workspace-layout-overlay")
        assertContains(css, ".workspace-layout-overlay-item")
        assertContains(css, ".resource-explorer")
        assertContains(css, ".resource-explorer-search")
        assertContains(css, ".resource-explorer-tree")
        assertContains(css, ".resource-explorer-cell")
        assertContains(css, ".resource-explorer-tree .tree-cell:selected")
        assertContains(css, ".editable-table")
        assertContains(css, ".editable-table .table-cell:editing")
        assertContains(css, ".editable-table-action")
        assertContains(css, ".data-grid")
        assertContains(css, ".data-grid-toolbar")
        assertContains(css, ".data-grid-search")
        assertContains(css, ".data-grid-table")
        assertContains(css, ".data-grid-row-dirty")
        assertContains(css, ".data-grid-footer")
        assertContains(css, ".data-grid-empty")
        assertContains(css, ".inspector-panel")
        assertContains(css, ".inspector-panel-header")
        assertContains(css, ".inspector-panel-title")
        assertContains(css, ".inspector-panel-metadata")
        assertContains(css, ".inspector-panel-section")
        assertContains(css, ".inspector-panel-property")
        assertContains(css, ".inspector-panel-actions")
        assertContains(css, ".button.inspector-panel-action")
        assertContains(css, ".inspector-panel-empty")
        assertContains(css, ".activity-timeline")
        assertContains(css, ".activity-timeline-group")
        assertContains(css, ".activity-timeline-row")
        assertContains(css, ".activity-timeline-marker")
        assertContains(css, ".activity-timeline-connector")
        assertContains(css, ".activity-timeline-event")
        assertContains(css, ".activity-timeline-action")
        assertContains(css, ".activity-timeline-row.tone-success .activity-timeline-marker")
        assertContains(css, ".command-palette")
        assertContains(css, ".command-palette-scrim")
        assertContains(css, ".command-palette-card")
        assertContains(css, ".command-palette-search")
        assertContains(css, ".command-palette-row")
        assertContains(css, ".command-palette-row-selected")
        assertContains(css, ".command-palette-title")
        assertContains(css, ".command-palette-group")
        assertContains(css, ".command-palette-empty")
    }

    @Test
    fun `all built in themes render stylesheet from tokens`() {
        BuiltInThemes.all.forEach { theme ->
            val css = ThemeStylesheetFactory.render(theme)

            assertContains(css, "-fx-background-color: ${theme.tokens.colors.surface};")
            assertContains(css, "-fx-font-size: ${theme.tokens.typography.baseSize}px;")
            assertContains(css, "-fx-background-radius: ${theme.tokens.radius}px;")
            assertContains(css, "-fx-background-color: ${theme.tokens.states.controlHover};")
            assertContains(css, "-fx-background-color: ${theme.tokens.states.surfaceHover};")
            assertContains(css, "-fx-opacity: ${theme.tokens.states.disabledOpacity};")
            assertContains(css, "-fx-effect: ${theme.tokens.elevation.card};")
            assertContains(css, "-fx-effect: ${theme.tokens.elevation.dropdown};")
            assertContains(css, "-fx-border-color: ${theme.tokens.colors.success};")
            assertContains(css, "-fx-border-color: ${theme.tokens.colors.warning};")
            assertContains(css, "-fx-border-color: ${theme.tokens.colors.danger};")
            assertContains(css, "-fx-border-color: ${theme.tokens.colors.info};")
        }
    }
}
