package dev.korafx.framework.theme

import kotlin.test.assertContains

internal fun assertAdvancedComponentStyles(css: String) {
    listOf(
        ".resource-explorer",
        ".resource-explorer-search",
        ".resource-explorer-breadcrumb",
        ".resource-explorer-empty-state",
        ".resource-explorer-tree",
        ".resource-explorer-tree .tree-cell:empty",
        ".resource-explorer-row-primary",
        ".resource-explorer-row-secondary",
        ".resource-explorer-row-status",
        ".resource-explorer-cell",
        ".resource-explorer-tree .tree-cell:selected",
        ".editable-table",
        ".editable-table-placeholder",
        ".editable-table-text-column .label",
        ".editable-table-cell-node",
        ".editable-table .table-cell:editing",
        ".editable-table-action",
        ".data-grid",
        ".data-grid-toolbar",
        ".data-grid-search",
        ".data-grid-toolbar-batch-action",
        ".data-grid-toolbar-snapshot-action",
        ".data-grid-column-visibility",
        ".data-grid-column-visibility-item",
        ".data-grid-table",
        ".data-grid-row-dirty",
        ".data-grid-footer",
        ".data-grid-selection-summary",
        ".data-grid-empty",
        ".virtual-list",
        ".virtual-list-list-view",
        ".virtual-table",
        ".virtual-table-table-view",
        ".virtual-table-cell-node",
        ".virtual-terminal",
        ".virtual-terminal-list-view",
        ".virtual-terminal-line-label",
        ".terminal-success .virtual-terminal-line-label",
        ".inspector-panel",
        ".inspector-panel-header",
        ".inspector-panel-title",
        ".inspector-panel-metadata",
        ".inspector-panel-section",
        ".inspector-panel-property",
        ".inspector-panel-actions",
        ".button.inspector-panel-action",
        ".inspector-panel-empty",
        ".activity-timeline",
        ".activity-timeline-group",
        ".activity-timeline-row",
        ".activity-timeline-marker",
        ".activity-timeline-connector",
        ".activity-timeline-event",
        ".activity-timeline-action",
        ".activity-timeline-row.tone-success .activity-timeline-marker",
        ".command-palette",
        ".command-palette-scrim",
        ".command-palette-card",
        ".command-palette-search",
        ".command-palette-row",
        ".command-palette-row-selected",
        ".command-palette-title",
        ".command-palette-group",
        ".command-palette-empty",
        ".code-editor",
        ".code-editor-toolbar",
        ".code-editor-search",
        ".code-editor-search-field",
        ".code-editor-replace-label",
        ".code-editor-replace-field",
        ".code-editor-frame",
        ".code-editor-line-numbers",
        ".code-editor-line-number-active",
        ".code-editor-area",
        ".code-editor-status",
        ".code-editor-status-text",
        ".source-editor",
        ".source-editor-toolbar",
        ".source-editor-action",
        ".source-editor-status",
        ".source-editor-status-message",
        ".source-editor-status-badge",
        ".source-editor-diagnostics",
        ".source-editor-diagnostic",
        ".source-editor-result",
        ".source-editor-diagnostic.tone-warning",
    ).forEach { selector ->
        assertContains(css, selector)
    }
}
